export const SELECTED_WORKS = [
  {
    id: 0,
    type: "SELECTED WORKS /",
    slug: "shopper-hopper",
    name: "Shopper Hopper",
    code: "SW/06",
    client: "Google Store",
    date: "2022",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
  {
    id: 1,
    slug: "youtube-united",
    name: "YouTube United",
    code: "SW/05",
    client: "YouTube",
    date: "2022",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
  {
    id: 2,
    slug: "pyramids-of-meroe",
    name: "Pyramids of Meroë",
    code: "SW/04",
    client: "Google Arts & Culture",
    date: "2021",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
  {
    id: 3,
    slug: "digital-assets-demystified",
    name: "Digital Assets Demystified",
    code: "SW/03",
    client: "Financial Times",
    date: "2021",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
  {
    id: 4,
    slug: "visit-planet-her",
    name: "Visit Planet Her",
    code: "SW/02",
    client: "Sony Music x Doja Cat",
    date: "2021",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
  {
    id: 5,
    slug: "xxim-records",
    name: "XXIM Records",
    code: "SW/01",
    client: "XXIM Records",
    date: "2020",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis libero, ullamcorper non ligula ut, finibus commodo eros. Sed congue, sem sed rutrum aliquam, urna enim pulvinar tortor, tincidunt feugiat lorem orci sed augue.",
    roles: ["Lead", "WebGL", "Frontend", "Backend"],
    url: "https://www.google.com",
    video: "/videos/projects/placeholder_video.mp4",
  },
];
