export const SELECTED_WORKS = [
  {
    id: 0,
    type: "SELECTED WORKS /",
    slug: "shopper-hopper",
    name: "Shopper Hopper",
    code: "SW/06",
    client: "Google Store",
    date: "2022",
    color: "#92D9EB",
  },
  {
    id: 1,
    slug: "youtube-united",
    name: "YouTube United",
    code: "SW/05",
    client: "YouTube",
    date: "2022",
    color: "#FF0000",
  },
  {
    id: 2,
    slug: "pyramids-of-meroe",
    name: "Pyramids of Meroë",
    code: "SW/04",
    client: "Google Arts & Culture",
    date: "2021",
    color: "#FFF6EB",
  },
  {
    id: 3,
    slug: "digital-assets-demystified",
    name: "Digital Assets Demystified",
    code: "SW/03",
    client: "Financial Times",
    date: "2021",
    color: "#0A4869",
  },
  {
    id: 4,
    slug: "visit-planet-her",
    name: "Visit Planet Her",
    code: "SW/02",
    client: "Sony Music x Doja Cat",
    date: "2021",
    color: "#FFDBFD",
  },
  {
    id: 5,
    slug: "xxim-records",
    name: "XXIM Records",
    code: "SW/01",
    client: "XXIM Records",
    date: "2020",
    color: "#7D7D7D",
  },
];
