export const AWARDS = [
  {
    code: "AW/15",
    name: "Foam Talent Digital 2024-2025 / General-Art - People's Lovie Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2024",
  },
  {
    code: "AW/14",
    name: "Foam Talent Digital 2024-2025 / General-Art - Gold Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2024",
  },
  {
    code: "AW/13",
    name: "Foam Talent Digital 2024-2025 / Best Use of Photography or Video - Silver Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2024",
  },
  {
    code: "AW/12",
    name: "Polaroid I-2 / Craft - Best Design - Gold Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2024",
  },
  {
    code: "AW/11",
    name: "Polaroid I-2 / General-Retail & Shopping - Gold Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2024",
  },
  {
    code: "AW/10",
    name: "Polaroid I-2 / Developer Award",
    url: "https://www.awwwards.com/sites/polaroid-i-2",
    organisation: "Awwwards",
    year: "2023",
  },
  {
    code: "AW/09",
    name: "Polaroid I-2 / Site of the Day",
    url: "https://www.awwwards.com/sites/polaroid-i-2",
    organisation: "Awwwards",
    year: "2023",
  },
  {
    code: "AW/08",
    name: "Pyramids of Meroë / Best Use Of Augmented Reality - People's Voice Winner",
    url: "https://winners.webbyawards.com/2023/ai-metaverse-virtual/metaverse-immersive-features/best-use-of-augmented-reality/237286/pyramids-of-mero",
    organisation: "Webby Awards",
    year: "2023",
  },
  {
    code: "AW/07",
    name: "Pyramids of Meroë / Cultural Institutions - Gold Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2022",
  },
  {
    code: "AW/06",
    name: "Pyramids of Meroë / Best Use Of Augmented Reality - People's Lovie Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2022",
  },
  {
    code: "AW/05",
    name: "Pyramids of Meroë / Best Use Of Augmented Reality - Bronze Award",
    url: "https://winners.lovieawards.com/",
    organisation: "The Lovie Awards",
    year: "2022",
  },
  {
    code: "AW/04",
    name: "Pyramids of Meroë / Developer Award",
    url: "https://www.awwwards.com/sites/pyramids-of-meroe",
    organisation: "Awwwards",
    year: "2022",
  },
  {
    code: "AW/03",
    name: "Pyramids of Meroë / Site Of The Day",
    url: "https://www.awwwards.com/sites/pyramids-of-meroe",
    organisation: "Awwwards",
    year: "2022",
  },
  {
    code: "AW/02",
    name: "Pyramids of Meroë / FWA Of The Day",
    url: "https://thefwa.com/cases/pyramids-of-meroe",
    organisation: "FWA",
    year: "2022",
  },
  {
    code: "AW/01",
    name: "Visit Planet Her / FWA Of The Day",
    url: "https://thefwa.com/cases/doja-cat-interstellher-air",
    organisation: "FWA",
    year: "2021",
  },
];
