export const OTHER_WORKS = [
  {
    name: "Aiconic",
    url: "https://aiconic.com/",
    code: "OW/09",
    client: "Aiconic",
    date: "2024",
  },
  {
    name: "Stellar Development",
    url: "https://www.stellardevelopment.eu/",
    code: "OW/08",
    client: "Stellar Development",
    date: "2024",
  },
  {
    name: "The Balvenie",
    url: "https://thebalvenie.com/",
    code: "OW/07",
    client: "William Grant & Sons",
    date: "2024",
  },
  {
    name: "Moooi",
    url: "https://www.moooi.com/uk",
    code: "OW/06",
    client: "Moooi",
    date: "2023",
  },
  {
    name: "Digital Sovereignty Explorer",
    url: "https://cloudsovereignty.withgoogle.com/",
    code: "OW/05",
    client: "Google Cloud",
    date: "2023",
  },
  {
    name: "Space Shelter",
    url: "https://spaceshelter.withgoogle.com/",
    code: "OW/04",
    client: "Google",
    date: "2021",
  },
  {
    name: "Speechmatics",
    url: "https://speechmatics.com",
    code: "OW/03",
    client: "Speechmatics",
    date: "2021",
  },
  {
    name: "Take me to the club",
    url: "https://www.phantom.land/projects/take-me-to-the-club",
    code: "OW/02",
    client: "PHANTOM",
    date: "2021",
  },
  {
    name: "What kind of sad girl are you?",
    url: "https://www.phantom.land/projects/sasha-sloan",
    code: "OW/01",
    client: "Sony Music x Sasha Sloan",
    date: "2020",
  },
];
