export const SELECTED_WORKS = [
  {
    id: 0,
    name: "Alt.ai",
    code: "SW/09",
    client: "Alt Ai",
    date: "2025",
    href: "https://alt.ai/",
  },
  {
    id: 1,
    name: "Foam Talent Digital 2024-2025",
    code: "SW/08",
    client: "Foam",
    date: "2024",
    href: "https://www.foam.org/talent-2024",
  },
  {
    id: 2,
    name: "Polaroid I-2",
    code: "SW/07",
    client: "Polaroid",
    date: "2023",
    href: "https://i2-camera.polaroid.com/",
  },
  {
    id: 3,
    name: "Shopper Hopper",
    code: "SW/06",
    client: "Google Store",
    date: "2022",
    href: "https://www.phantom.land/projects/shopper-hopper",
  },
  {
    id: 4,
    name: "Think Football",
    code: "SW/05",
    client: "YouTube",
    date: "2022",
    href: "https://www.phantom.land/projects/think-football",
  },
  {
    id: 5,
    name: "Pyramids of Meroë",
    code: "SW/04",
    client: "Google Arts & Culture",
    date: "2021",
    href: "https://artsexperiments.withgoogle.com/meroe/",
  },
  {
    id: 6,
    name: "Digital Assets Demystified",
    code: "SW/03",
    client: "Financial Times",
    date: "2021",
    href: "https://adhesive-spice-b7b.notion.site/Phantom-x-Financial-Times-Digital-Assets-Demystified-1bf70acb2c3480869de7e50ae78aa160",
  },
  {
    id: 7,
    name: "Visit Planet Her",
    code: "SW/02",
    client: "Sony Music x Doja Cat",
    date: "2021",
    href: "https://www.phantom.land/projects/doja-cat-planet-her",
  },
  {
    id: 8,
    name: "XXIM Records",
    code: "SW/01",
    client: "XXIM Records",
    date: "2020",
    href: "https://www.xximrecords.com/",
  },
];
