export const SELECTED_WORKS = [
  {
    id: 0,
    type: "SELECTED WORKS /",
    slug: "shopper-hopper",
    name: "Shopper Hopper",
    code: "SW/06",
    client: "Google Store",
    date: "2022",
    description:
      "Hopping past the black friday crowds, Shopper Hopper is a digital game with physical print-based components that exhibits the ease of online shopping through a voxel-based 3D infinite runner. Built for Google Store at PHANTOM.",
    roles: ["WebGL", "Frontend", "Backend"],
    url: "https://shopperhopper.withgoogle.com",
    video: "/videos/projects/shopper_hopper.mp4",
  },
  {
    id: 1,
    slug: "youtube-united",
    name: "YouTube United",
    code: "SW/05",
    client: "YouTube",
    date: "2022",
    description:
      "Building fanfare through friendly competition, YouTube United was a digital game and physical installation that pit expo attendees' World Cup trivia knowledge against each others. Built for YouTube at PHANTOM.",
    roles: ["Frontend", "Backend"],
    video: "/videos/projects/youtube_united.mp4",
  },
  {
    id: 2,
    slug: "pyramids-of-meroe",
    name: "Pyramids of Meroë",
    code: "SW/04",
    client: "Google Arts & Culture",
    date: "2021",
    description:
      "Exploring the ancient capital of the Kushite, Pyramids of Meroë is a 3D narrative scrolling experience that navigates various archeological structures at the site. Built for Google Arts & Culture with Google Brand Studio at PHANTOM.",
    roles: ["Frontend", "Audio"],
    url: "https://artsexperiments.withgoogle.com/meroe/",
    video: "/videos/projects/pyramids_of_meroe.mp4",
  },
  {
    id: 3,
    slug: "digital-assets-demystified",
    name: "Digital Assets Demystified",
    code: "SW/03",
    client: "Financial Times",
    date: "2021",
    description:
      "Serving bespoke educational articles, Digital Assets Demystified is a questionnaire based article series that guides the user through the content based on their familiarity. Built for Financial Times at PHANTOM.",
    roles: ["Frontend"],
    url: "https://digitalassetsdemystified.ft.com/",
    video: "/videos/projects/digital_assets_demystified.mp4",
  },
  {
    id: 4,
    slug: "visit-planet-her",
    name: "Visit Planet Her",
    code: "SW/02",
    client: "Sony Music x Doja Cat",
    date: "2021",
    description:
      "Prepping Doja Cat fans for launch, Visit Planet Her was a multi-stage Spotify-driven 3D narrative that took users all the way through a gamified flight booking process to their pre-album launch party destination. Built for Sony Musix x Doja Cat at PHANTOM.",
    roles: ["Frontend", "Backend"],
    video: "/videos/projects/visit_planet_her.mp4",
  },
  {
    id: 5,
    slug: "xxim-records",
    name: "XXIM Records",
    code: "SW/01",
    client: "XXIM Records",
    date: "2020",
    description:
      "Exploring music through motion, XXIM Records label launch page was an audio-driven label launch site that highlighted newly signed artists and their new releases. Built for XXIM Records at PHANTOM.",
    roles: ["Frontend", "Audio"],
    video: "/videos/projects/xxim.mp4",
  },
];
